import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { MainNav } from "@/components/main-nav"
import { Toaster } from "@/components/ui/sonner"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="border-b">
          <div className="flex h-16 items-center px-4">
            <h1 className="text-lg font-bold mr-4">成交系統</h1>
            <MainNav className="mx-6" />
          </div>
        </div>
        <main className="flex-1 p-4 md:p-8 pt-6">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
